import Head from "next/head";
import { useRouter } from "next/router";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";
import CollectionSection from "../components/home/collection";
import HowItWorks from "../components/home/how-it-works";
import ReserveSection from "../components/home/reserve";

export default function Home() {
  const router = useRouter();
  return (
    // <Head>
    //   <title>Create Next App</title>
    //   <meta name="description" content="Generated by create next app" />
    //   <link rel="icon" href="/favicon.ico" />
    // </Head>
    <>
      {" "}
      <div className="bg-darkNavyBlue">
        <div className="max-w-[1300px] mx-auto px-5 md:px-10 mb-20">
          <div className="flex flex-col lg:flex-row pt-5 lg:pt-10 mb-20 gap-5">
            <div className="w-full lg:w-1/2 text-[#fff] pt-6 lg:pt-16">
              <h1 className="text-4xl text-center lg:text-start font-bold mb-8 max-w-[480px] mx-auto lg:mx-0">
                Use your NFT as Collateral to borrow MATIC or lend your MATIC to
                earn yields instantly
              </h1>
              <div className="flex flex-col sm:flex-row gap-5 justify-center lg:justify-start">
                <button className="bg-[#cb2d83] py-4 px-20 ">Deposit</button>
                <button
                  className="bg-[#7e5bd6] py-2 px-20"
                  onClick={() => router.push("/borrow")}
                >
                  Borrow
                </button>
              </div>
            </div>
            <div className="w-full lg:w-1/2 mt-10 lg:mt-0 h-[400px]">
              <div className="flex">
                <div
                  className="h-[200px] w-[50%] bg-black rounded-t-md"
                  style={{
                    backgroundImage: `url(
                    https://svc.blockdaemon.com/nft/v1/ethereum/mainnet/media/token/0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB/6b9d0a00-5449-5887-8ab7-ff83901356d4.png?apiKey=bjsefVm7mtztpB4LzHNyII8TQJ4jgSPn5vIouexxiAOtSJU-
                  )`,

                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                  }}
                ></div>
                <div
                  className="h-[200px] w-[50%] bg-black rounded-t-md ml-auto"
                  style={{
                    backgroundImage: `url(
                    https://svc.blockdaemon.com/nft/v1/ethereum/mainnet/media/token/0x0c3A405727dEa8C9FA51FD931ed223535412F7Ac/4acae743-0516-508f-b3bb-81c3403a2f5b.gif?apiKey=bjsefVm7mtztpB4LzHNyII8TQJ4jgSPn5vIouexxiAOtSJU-
                  )`,

                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                  }}
                ></div>
              </div>
              <div className="flex">
                <div
                  className="h-[200px] w-[50%] bg-black rounded-t-md mr-auto"
                  style={{
                    backgroundImage: `url(
                    https://svc.blockdaemon.com/nft/v1/ethereum/mainnet/media/collection/8d86e4e9-b95f-5c3d-ac90-b4573ddc721e/logo.gif?apiKey=bjsefVm7mtztpB4LzHNyII8TQJ4jgSPn5vIouexxiAOtSJU-
                  )`,

                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                  }}
                ></div>
                <div
                  className="h-[200px] w-[50%] bg-black rounded-t-md mr-auto"
                  style={{
                    backgroundImage: `url(
                    https://svc.blockdaemon.com/nft/v1/ethereum/mainnet/media/token/0xd02d577880b9d5cec5eee787652527C8Ac8294eE/803e93f1-7c12-526f-8380-a5baa20511cd.png?apiKey=bjsefVm7mtztpB4LzHNyII8TQJ4jgSPn5vIouexxiAOtSJU-
                  )`,

                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                  }}
                ></div>
              </div>
            </div>
          </div>

          <HowItWorks />

          <CollectionSection />
          <ReserveSection />
        </div>
      </div>
    </>
  );
}
